import Head from 'next/head'




export default function Home() {
  return (
    <>
      <Head>
        <title>Mi primera chamba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
        
      </Head>
      <main className=''>
        <div className='cool-font'> Hola mundo</div>
        <div class="container text-center">
  <div className="row">
    <div className="col-4">
    <div className='col1'> Hola mundo</div>
    </div>
    <div className="col-8">
      2 of 2
    </div>
  </div>
  <div className="row">
    <div className="col">
      1 of 3
    </div>
    <div className="col">
      2 of 3
    </div>
    <div className="col">
      3 of 3
    </div>
  </div>
</div>
            
       

        
      
            
      
      </main>
    </>
  )
}
